# Generated by Django 2.0.7 on 2018-09-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180909_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
