# Generated by Django 2.0.8 on 2018-08-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180815_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='email',
            field=models.EmailField(blank=True, max_length=255, unique=True, verbose_name='Email address'),
        ),
    ]
