# Generated by Django 2.0.8 on 2018-09-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180815_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='account/%Y/%m/%d', verbose_name='프로필 사진'),
        ),
        migrations.AlterField(
            model_name='user',
            name='in_short',
            field=models.CharField(blank=True, max_length=255, verbose_name='한마디'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=30, unique=True, verbose_name='닉네임'),
        ),
    ]
