# Generated by Django 2.0.8 on 2018-09-08 10:29

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_summernote', '0002_update-help_text'),
        ('account', '0007_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.AddField(
            model_name='note',
            name='attachment_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_summernote.Attachment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=django_summernote.fields.SummernoteTextField(default=''),
        ),
    ]
