# Generated by Django 2.0.8 on 2018-09-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180908_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='attachment_ptr',
        ),
        migrations.AddField(
            model_name='note',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
    ]
