# Generated by Django 2.0.8 on 2018-08-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeboard',
            name='title',
            field=models.CharField(max_length=40, verbose_name='title'),
        ),
    ]
