# Generated by Django 2.0.7 on 2018-08-22 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbs', '0007_auto_20180821_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', django_summernote.fields.SummernoteTextField(default='')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorable_Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_set', to='bbs.Favorable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='favorable',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='Favorable_like_user_set', through='bbs.Favorable_Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
