# Generated by Django 2.0.7 on 2018-08-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0008_auto_20180822_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorable_like',
            name='title',
            field=models.CharField(default=1, max_length=20, verbose_name='title'),
            preserve_default=False,
        ),
    ]
