# Generated by Django 2.0.7 on 2018-08-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0009_favorable_like_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorable',
            name='post',
        ),
        migrations.RemoveField(
            model_name='favorable_like',
            name='title',
        ),
        migrations.AddField(
            model_name='favorable',
            name='content',
            field=models.CharField(default=1, max_length=20, verbose_name='content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorable',
            name='title',
            field=models.CharField(default=2, max_length=20, verbose_name='title'),
            preserve_default=False,
        ),
    ]
