# Generated by Django 2.0.8 on 2018-08-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0011_favorable_photo'),
        ('bbs', '0009_auto_20180822_1157'),
    ]

    operations = [
    ]
