# Generated by Django 2.0.8 on 2018-08-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0014_auto_20180823_1432'),
        ('bbs', '0016_auto_20180823_1635'),
    ]

    operations = [
    ]
