# Generated by Django 2.0.8 on 2018-08-23 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0018_auto_20180823_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspendrequestcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='suspendrequestcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='suspendrequestdislike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='suspendrequestdislike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='suspendrequestlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='suspendrequestlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='withcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='withcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='withdislike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='withdislike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='withlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='withlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='suspendrequest',
            name='dislike_user_set',
        ),
        migrations.RemoveField(
            model_name='suspendrequest',
            name='like_user_set',
        ),
        migrations.RemoveField(
            model_name='suspendrequest',
            name='views',
        ),
        migrations.RemoveField(
            model_name='with',
            name='dislike_user_set',
        ),
        migrations.RemoveField(
            model_name='with',
            name='like_user_set',
        ),
        migrations.RemoveField(
            model_name='with',
            name='views',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='dislike_user_set',
            field=models.ManyToManyField(blank=True, related_name='GCdislike_user_set', through='bbs.GalleryDisLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='Glike_user_set', through='bbs.GalleryLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gallerycomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbs_gallerycomments', to='bbs.Gallery', verbose_name='HoneyTip Comment'),
        ),
        migrations.AlterField(
            model_name='gallerydislike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike_set', to='bbs.Gallery'),
        ),
        migrations.AlterField(
            model_name='gallerylike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_set', to='bbs.Gallery'),
        ),
        migrations.DeleteModel(
            name='SuspendRequestComment',
        ),
        migrations.DeleteModel(
            name='SuspendRequestDisLike',
        ),
        migrations.DeleteModel(
            name='SuspendRequestLike',
        ),
        migrations.DeleteModel(
            name='WithComment',
        ),
        migrations.DeleteModel(
            name='WithDisLike',
        ),
        migrations.DeleteModel(
            name='WithLike',
        ),
    ]
