# Generated by Django 2.0.8 on 2018-09-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0034_auto_20180906_1335'),
        ('bbs', '0031_auto_20180907_1547'),
    ]

    operations = [
    ]
