# Generated by Django 2.0.8 on 2018-09-06 13:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk_bbs', '0006_auto_20180828_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='CKPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
