# Generated by Django 2.0.8 on 2018-09-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bk_bbs', '0007_ckpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CKPost',
        ),
    ]
